version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "8080:81"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

